# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:9.2
    build:
      context: ./
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  adminer:
    image: adminer
    build:
      context: .
    restart: always
    ports:
      - 8080:8080

  api-python:
    image: python_image
    build:
      context: ./server/
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=db
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
        
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000
  
  react: 
    image: react
    build: ./my-app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8000
    volumes:
      - ./my-app:/app
      - /app/node_modules
    depends_on:
      - api-python
    command: npm start